version: '3.4'

name: AirlineBookingSystem
services:
  abs-auth:
    build:
      context: .
      dockerfile: ABS-Auth/Dockerfile
    ports:
      - 5001:5001

  abs-sectionairlineairport:
    build:
      context: .
      dockerfile: Abs-SectionAirlineAirport/Dockerfile
    ports:
      - 5004:5004


  abs-gateway:
    build:
      context: .
      dockerfile: ABS-Gateway/Dockerfile
    ports:
      - 5000:5000
    networks:
      - my-network


  abs-flights:
    build:
      context: .
      dockerfile: ABS-Flights/Dockerfile
    ports:
      - 5002:5002
      
  abs-tickets:
    build:
      context: .
      dockerfile: ABS-Tickets/Dockerfile
    ports:
      - 5003:5003

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal 
networks:
    my-network:
        driver: bridge
      

