version: '3.4'

services:
  abs-auth:
    image: ${DOCKER_REGISTRY-}auth
    build:
      context: .
      dockerfile: ABS-Auth/Dockerfile
    ports:
      - 5001:5001

  abs-sectionairlineairport:
    image: ${DOCKER_REGISTRY-}create
    build:
      context: .
      dockerfile: Abs-SectionAirlineAirport/Dockerfile
    ports:
      - 5004:5004


  abs-gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: ABS-Gateway/Dockerfile
    ports:
      - 5000:5000


  abs-flights:
    image: ${DOCKER_REGISTRY-}flights
    build:
      context: .
      dockerfile: ABS-Flights/Dockerfile
    ports:
      - 5002:5002
      
  abs-tickets:
    image: ${DOCKER_REGISTRY-}tickets
    build:
      context: .
      dockerfile: ABS-Tickets/Dockerfile
    ports:
      - 5003:5003

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal 

  #dynamoTablesInit:
  #  image: garland/aws-cli-docker
  #  command: "aws dynamodb create-table --table-name ABS-Table \ 
  #              --attribute-definitions \ 
  #                  AttributeName=PK,AttributeType=S \ 
  #                  AttributeName=SK,AttributeType=S \
  #              --key-schema \
  #                  AttributeName=PK,KeyType=HASH \
  #                  AttributeName=SK,KeyType=RANGE \
  #              --global-secondary-indexes \
  #                  \"[ \
  #                      \"Create\": { \
  #                          \"IndexName\": \"GSI1\", \
  #                          \"KeySchema\": [{\"AttributeName\":\"PK\",\"KeyType\":\"HASH\"}], \
  #                       \"Projection\":{ \
  #                          \"ProjectionType\":\"ALL\" \
  #                  }, \
  #                  \"Create\": { \
  #                          \"IndexName\": \"GSI2\", \
  #                          \"KeySchema\": [{\"AttributeName\":\"PK\",\"KeyType\":\"HASH\"}], \
  #                       \"Projection\":{ \
  #                          \"ProjectionType\":\"ALL\" \
  #                  } \
  #                  ]\" \
  #              --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 \
  #              --endpoint-url http://host.docker.internal:8000"
  #  links:
  #  - dynamodb-local

