USE [master]
Go
CREATE DATABASE AirlineBookingSystem;
GO
USE AirlineBookingSystem;
GO
CREATE TYPE PasswordType FROM NVARCHAR(300) NOT NULL;
CREATE TYPE UsernameType FROM NVARCHAR(50) NOT NULL 
CREATE TYPE EmailType FROM NVARCHAR(100) NOT NULL
CREATE TYPE UserIdType FROM NVARCHAR(255)
GO

CREATE TABLE Airlines(
	Id INTEGER PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(6) NOT NULL UNIQUE
);

CREATE TABLE Airports(
	Id INTEGER PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(3) NOT NULL UNIQUE,
);

CREATE TABLE Flights(
	Id INTEGER PRIMARY KEY IDENTITY,
	FlightNumber NVARCHAR(50) UNIQUE NOT NULL,
	DepartureDate DATETIME NOT NULL,
	LandingDate DATETIME NOT NULL,
	AirlineId INTEGER FOREIGN KEY REFERENCES Airlines(Id) NOT NULL,
	OriginAirportId INTEGER FOREIGN KEY REFERENCES Airports(Id) NOT NULL,
	DestinationAirportId INTEGER FOREIGN KEY REFERENCES Airports(Id) NOT NULL,
	CONSTRAINT Ck_Airports_Difference CHECK (OriginAirportId <> DestinationAirportId)
)

CREATE TABLE Sections(
	Id INTEGER PRIMARY KEY IDENTITY,
	AvailableSeatsCount INTEGER NOT NULL,
	[Rows] INTEGER,
	[Columns] INTEGER,
	SeatClass INTEGER,
	FlightId INTEGER FOREIGN KEY REFERENCES Flights(Id) ON DELETE CASCADE NOT NULL ,
	CONSTRAINT Ck_Rows_Cols CHECK ([Rows] > 0 AND [Columns] > 0)
);

CREATE TABLE Seats(
	Id INTEGER PRIMARY KEY IDENTITY,
	[Row] INTEGER,
	[Column] INTEGER,
	IsBooked BIT DEFAULT 0,
	SectionId INTEGER FOREIGN KEY REFERENCES Sections(Id) ON DELETE CASCADE NOT NULL,
	CONSTRAINT Ck_Booked_Value CHECK (IsBooked IN (0,1))
)

CREATE TABLE [Roles](
	Id INTEGER PRIMARY KEY IDENTITY,
	[Name] NVARCHAR(50) NOT NULL UNIQUE,
)
CREATE TABLE Users(
	Id UserIdType PRIMARY KEY,
	Username UsernameType UNIQUE,
	Email EmailType UNIQUE,
	[Status] INTEGER,
	PasswordHash PasswordType,
	Salt NVARCHAR(300),
	CONSTRAINT Status_Value CHECK ([Status] IN (0,1,2))
)

CREATE TABLE UserRoles(
	Id INTEGER PRIMARY KEY IDENTITY,
	UserId NVARCHAR(255) FOREIGN KEY REFERENCES Users(Id) ON DELETE CASCADE NOT NULL ,
	RoleId INTEGER FOREIGN KEY REFERENCES Roles(Id) ON DELETE CASCADE NOT NULL
)

CREATE TABLE Tickets (
	Id INTEGER PRIMARY KEY IDENTITY,
	PassengerName NVARCHAR(50) NOT NULL,
	FlightId INTEGER FOREIGN KEY REFERENCES Flights(Id) NOT NULL,
	SeatId INTEGER FOREIGN KEY REFERENCES Seats(Id) ON DELETE CASCADE NOT NULL,
	UserId NVARCHAR(255) FOREIGN KEY  REFERENCES Users(Id) NOT NULL

)

CREATE TABLE ErrorCodes(
 Id INTEGER PRIMARY KEY IDENTITY,
 Number INTEGER NOT NULL UNIQUE,
 [Name] NVARCHAR(100) NOT NULL
)

ALTER TABLE Seats 
ADD TicketId INTEGER FOREIGN KEY REFERENCES Tickets(Id)

ALTER TABLE UserRoles
ADD CONSTRAINT AK_UserRoles UNIQUE (UserId , RoleID)

ALTER TABLE Sections
ADD CONSTRAINT Ck_ColsRange CHECK ([Columns] <= 10)


ALTER TABLE Sections
ADD CONSTRAINT Ck_RowsRange CHECK ([Rows] <= 100)

ALTER TABLE Seats
ADD CONSTRAINT AK_Seats UNIQUE ([Row] , [Column] , [SectionId])

ALTER TABLE ErrorCodes
ADD CONSTRAINT Ck_Number CHECK (Number > 50000)